name: Release TP

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:    
      - 'releases/[0-9]+.[0-9]+'

env:
  PROJECT_NAME: Grupo_2
  PROJECT_PATH: TGC.MonoGame.TP
  PRERELEASE: true

jobs:
  build-project:
    name: Publish Project
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Build Windows
      run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release --output artifacts/windows
    - name: Build Osx
      run: dotnet publish ${{ env.PROJECT_PATH }} -r osx-x64 -c Release --output artifacts/osx
    - name: Build Linux
      run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 -c Release --output artifacts/linux
    - name: Copy license and readme
      run: |
        copy LICENSE artifacts
        copy README.md artifacts
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-build
        path: artifacts/

  version:
    name: Get and upload version number
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get version from tag
      run: |
        echo $(git describe --tags --abbrev=0) > version.txt
    - name: Upload version
      uses: actions/upload-artifact@v3
      with:
        name: release-version
        path: version.txt

  release-project:
    name: Release Project
    runs-on: ubuntu-20.04
    needs: build-project

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Retrieve version
      run: |
        echo "TAGVERSION=$(cat release-version/version.txt | tail -c +2)" >> $GITHUB_ENV
    - name: Package release
      run: |
        chmod 755 dotnet-build/windows/${{ env.PROJECT_PATH }}.exe dotnet-build/linux/${{ env.PROJECT_PATH }} dotnet-build/osx/${{ env.PROJECT_PATH }}
        echo dotnet-build/windows dotnet-build/linux dotnet-build/osx | xargs -n 1 cp dotnet-build/LICENSE dotnet-build/README.md
        mv dotnet-build/windows ${{ env.PROJECT_NAME }} && zip -r release-windows.zip ${{ env.PROJECT_NAME }} && rm -rf ${{ env.PROJECT_NAME }}
        mv dotnet-build/linux ${{ env.PROJECT_NAME }} && zip -r release-linux.zip ${{ env.PROJECT_NAME }} && rm -rf ${{ env.PROJECT_NAME }}
        mv dotnet-build/osx ${{ env.PROJECT_NAME }} && zip -r release-osx.zip ${{ env.PROJECT_NAME }} && rm -rf ${{ env.PROJECT_NAME }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ env.TAGVERSION }}
        release_name: Release Versión ${{ env.TAGVERSION }}
        body: |
          TGC ${{ env.PROJECT_NAME }} - Versión ${{ env.TAGVERSION }}  

          Integrantes:
          - Iván De Luca
          - Etc. Etc.
        draft: false
        prerelease: ${{ env.PRERELEASE }}
    - name: Upload Release Windows
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-windows.zip
        asset_name:  ${{ env.PROJECT_NAME }}-v${{ env.TAGVERSION }}-windows.zip
        asset_content_type: application/zip
    - name: Upload Release MacOS
      id: upload-release-asset-osx
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-osx.zip
        asset_name:  ${{ env.PROJECT_NAME }}-v${{ env.TAGVERSION }}-osx.zip
        asset_content_type: application/zip
    - name: Upload Release Linux
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-linux.zip
        asset_name:  ${{ env.PROJECT_NAME }}-v${{ env.TAGVERSION }}-linux.zip
        asset_content_type: application/zip
